apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-deployment
spec:
  selector:
    matchLabels:
      app: ws
  template:
    metadata:
      labels:
        app: ws
    spec:
      containers:
        - name: ws
          image: scaling-ws
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: ws-service
spec:
  type: LoadBalancer
  selector:
    app: ws
  ports:
    - port: 3000
      targetPort: 3000
